# Site settings
title:         감귤왕
description:    "감귤의 온기가 남아있다"
url:            https://gamgyulwang.github.io

# Author
author:
  name:         gamgyulwang
  email:        wjjang42@gmail,com
  url:          https://github.com/gamgyulwang

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Related posts settings
related_posts_section:
  max_count:        5
  min_common_tags:  2

# Links to social media
social:
  email: wjjang42@gmail.com
  github: https://github.com/gamgyulwang 
  twitter: https://twitter.com
  linkedin: https://ba.linkedin.com/in/inela-avdic-hukic-322354131
